### PR TITLE
Add modifier keys to every keyboard and mouse input

### LINKED ISSUE #237: Modifier keys get stuck when switching away from the Graphite browser window/tab
The Shift, Ctrl, and Alt (modifier) keys get stuck when you use those keys to switch away from the browser window or tab running Graphite (for example, Alt-Tabbing). Then when you try to, for example, draw with a shape tool, it will get stuck in proportional scaling (Shift) and/or centered scaling (Alt). This also messes with the viewport keyboard shortcut navigation behavior (from #229). I believe the solution is to check the state of modifier keys any time that any input is processed and reset them to their current state, because the browser should be reporting the correct (non-stuck) value but we are only listening for modifier key state when modifier keys, rather than all forms of input, are received.

### PR DESCRIPTION
**Pull request by AyeTbk**
Closes #237

---
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/247)

### CODE REVIEW

**Comment by AyeTbk** [comment]
I've modified `InputPreprocessorMessage` so the messages also carry information about modifier keys currently pressed. Should it be exposed through the `EditorTestUtils` in `test_utils.rs` too? Right now, `EditorTestUtils` will just assume no modifier keys are pressed.

**Comment by Keavon** [comment]
> I've modified `InputPreprocessorMessage` so the messages also carry information about modifier keys currently pressed. Should it be exposed through the `EditorTestUtils` in `test_utils.rs` too? Right now, `EditorTestUtils` will just assume no modifier keys are pressed.

That should be fine, unless you want to take it upon yourself to write tests emulating the previous bug when a user Alt+Tabbed out of the window to ensure it stays functional. If you're the kind of person who likes to write tests, that would be wonderful if you want to take it upon yourself to go wild with tests. But I don't like to require people go through what is often a hassle except in areas of high likelihood of breakage.

**Review by Keavon — APPROVED** [review]

**Review by Keavon — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AyeTbk)

**Review by Keavon — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AyeTbk)

**Review by AyeTbk — COMMENTED** [review]
I don't mind writing tests, so long as I know what I'm testing... In this case, I think it would be to test that the InputPreprocessor updates its KeyStates taking into account the modifier keys stuff I added. Should I add a test module in input_preprocessor.rs?

> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/247#-:-MeNX8jIEbAWIQWRXF3o:b-ogsi1x)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AyeTbk)

**Comment by Keavon** [comment]
> I don't mind writing tests, so long as I know what I'm testing... In this case, I think it would be to test that the InputPreprocessor updates its KeyStates taking into account the modifier keys stuff I added. Should I add a test module in input_preprocessor.rs?
> 
> > _[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/247#-:-MeNX8jIEbAWIQWRXF3o:b-ogsi1x)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AyeTbk)

Certainly, that sounds like an excellent plan.

**Review by Keavon — APPROVED** [review]

**Review by Keavon — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AyeTbk)

**Pull request merged**
