### PR TITLE
Add export dialog option to set background color

### LINKED ISSUE #695: Export dialog option to set background color
It would be great to have another option in the export dialog: Background. It could be set to Artboard Background, Black, White, and Transparent.

- JPG would make Transparent grayed out.
- SVG would need to add a colored rectangle behind everything with dimensions equal to the viewBox bounds (except when Transparent is chosen).

### PR DESCRIPTION
**Pull request by brainwo**
Closes #695

### CODE REVIEW

**Comment by brainwo** [comment]
@KeatonTech mention you in case you don't see it. PR is ready.

**Comment by Keavon** [comment]
@brainwo I assume you meant to ping me instead. I shall take a look shortly! In the future, you can also just request me (or any relevant team members, if you happen to know who) as reviewers directly in GitHub. Or ping us, that works too :)

**Comment by brainwo** [comment]
@Keavon I can't assign any reviewers

**Comment by Keavon** [comment]
@brainwo Ah I didn't realize that, thanks for letting me know. Pinging is best then!

**Comment by Keavon** [comment]
My PR #784 will provide some simplification that your PR can utilize. So I'll defer a little longer until that's ready then review this so it can make use of those changes.

**Comment by Keavon** [comment]
Just an update @brainwo my branch is taking longer than I expected, so I haven't been able to review this yet because of the overlapping functionality and my singular focus on getting that feature shipped. I've given this the `hacktoberfest-accepted` tag for now so at least you get credit if you're signed up for Hacktoberfest. Sorry for the delay as I continue trying to get this big feature shipped (which overlaps with this one, due to an unfortunate confluence of timing).

**Comment by Keavon** [comment]
Please see my [comment](https://github.com/GraphiteEditor/Graphite/issues/695#issuecomment-1304968053) about the status of this. I'm marking this as a draft for now so I can stay organized until its changed are ready for review again later. Sorry again for the delay and the changes of requirements!

**Comment by Keavon** [comment]
Closing this for now since it isn't a priority for a core team member to revive this. Once we have node-based artboards soon, the need for this will change a lot.

**Pull request closed without merging**
