### PR TITLE
Fix: empty folder's disappearing when copying

### PR DESCRIPTION
**Pull request by Tiger3018**
TODO:

* [x] portfolio_message omit copy event of the empty folder

Related: #1452, #1633

### CODE REVIEW

**Comment by Tiger3018** [comment]
Notes:

For folder layers, `DocumentNode.inputs` seems to be [Child_node/Value, Sibling_node]. It's not well documented yet.

**Comment by 0HyperCube** [comment]
That is correct in the current main branch @Tiger3018, however @Keavon is currently reversing the ordering of those inputs (I'm unsure why) in a branch in someone's fork. For documentation on what the inputs are, you can look at the implementation (here the `ConstructLayerNode` struct) and also the `document_node_types.rs` file has a string name for the inputs to a node.

**Comment by Tiger3018** [comment]
For highlighting and group issues, it only appeared in `Just a Potted Cactus` and `Valley of Spires` example files. New document and two other example files didn't affected. Maybe a document version issue?

Mark this PR ready for review.

**Comment by Keavon** [comment]
!build

**Comment by Tiger3018** [comment]
This PR is not related to discovered issues formerly, and can be merged

**Comment by Keavon** [comment]
I'm sorry, I actually still can't figure out what this PR addresses. What was the original issue or todo item?

**Comment by Tiger3018** [comment]
@Keavon I have removed the `portfolio_message` to clarifying just the phenomenon in the PR title, and have removed the mention of new issue in the description.

**Comment by Keavon** [comment]
I'm still not sure precisely what this PR is about but I think it's already solved by the changes made in #1712 so I will close this as it's redundant.

**Pull request closed without merging**
