### PR TITLE
Upgrade npm dependencies and add "@parcel/config-default"

### PR DESCRIPTION
**Pull request by iacore**
"@parcel/config-default" is needed to run on other package managers like pnpm even though it seems to have worked okay on regular npm.

### CODE REVIEW

**Comment by Keavon** [comment]
@TrueDoctor can you help figure out what's wrong with the new GitHub Actions script/config which is causing CI to fail on this?

**Comment by TrueDoctor** [comment]
I think this might be due to the pr not originating from our repo, hence we don't have access to post comments to that repos pr

**Comment by TrueDoctor** [comment]
@iacore  you need to include your `package-lock.json` I tried to push mine but that seems to fail on the ci. You can try to push your version to see if that works

**Comment by iacore** [comment]
This is npm being strict.

https://github.com/HellButcher/parcel-transformer-svelte3-plus/pull/4

**Comment by Keavon** [comment]
Looks like that's updated and published!

**Review by Keavon — APPROVED** [review]
Thanks

**Pull request merged**
