### PR TITLE
Fix crash when scaling something with 0 width or height

### LINKED ISSUE #1043: Crash with zero scale
# Steps
- Open latest build https://dev.graphite.rs/
- Draw a rectangle
- Set the scale or dimensions to 0 in the properties panel by typing in the input field
- Confirm with enter
- Type a new number into the dimensions or scale field and press enter.
- `panicked at 'tried to transform point to non finite position', node-graph/gcore/src/vector/manipulator_point.rs:65:9`

### PR DESCRIPTION
**Pull request by Sahra-Zhou**
Avoided the crash and resolved NaN present in property panel when trying to change zero scale to some other value.

Closes #1043

### CODE REVIEW

**Review by 0HyperCube — APPROVED** [review]
Great work on this!

**Comment by Keavon** [comment]
One UX nitpick is that the properties panel keeps (displays) the nonzero value typed by the user, even though value remains zero. This gets reset back to 0 properly after the user refreshes the UI by switching to another selected layer and back. But we can fix that at another time.

**Comment by Keavon** [comment]
Hi @Sahra-Zhou, thanks again for this code contribution to the project! We're still hoping you will respond to the request to relicense this code. Please see #4208 ASAP, thank you!

**Comment by Keavon** [comment]
Hi @Sahra-Zhou, we're grateful of your past code contribution to Graphite, but unless we hear from you by the **end of this weekend** with agreement about relicensing your code to include the MIT license, we will begin steps to remove your code contributions **so that you will no longer be a Graphite code contributor**. We'd much rather avoid this outcome, so please respond now.

To agree, simply log into your GitHub account, visit https://github.com/GraphiteEditor/Graphite/pull/4208, and copy-paste this into a comment:

"I license my past and future contributions to Graphite under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option."

If you're hesitant because you disagree or have questions, feel free to respond with another message; we'll do our best to answer your questions or concerns. More explanation is at the top of the linked thread if you're confused. **So far, 164 contributors have agreed and you are among the 11% remaining** whom we are still hoping to hear from before we begin removing your code from the project starting this Monday. (If you only see this later than Monday, your future belated response will still be appreciated.)

Thank you for your cooperation and support of open source, and we hope you'll help us keep your valued contributions in-tact.

**Pull request merged**
