### PR TITLE
Re-add PartialEq removed in #230

### PR DESCRIPTION
**Pull request by 0HyperCube**
~~Remove more partialeq derives from the messaging system.~~ (Edit: see last comment.) Unblocks #220

---
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/232)

### CODE REVIEW

**Review by Keavon — APPROVED** [review]

**Comment by TrueDoctor** [comment]
wait a sec

**Comment by TrueDoctor** [comment]
We should evaluate it there is a good reason to require partial eq before just removing it

**Comment by Keavon** [comment]
Ok. I gave my approval but let's hold off until we can determine if this is the best course of action.

**Comment by TrueDoctor** [comment]
We will need an eq implementation for message deduplication which is why I initially put it there

**Comment by TrueDoctor** [comment]
We can have a discussion on if we can avoid requiring partial eq for that but it is a discussion we should have

**Comment by 0HyperCube** [comment]
When would messages be duplicated?

**Comment by TrueDoctor** [comment]
> When would messages be duplicated?

For example if you have multiple requests to update the canvas for example, you obviously only need to process the last one

**Comment by Keavon** [comment]
Summary from the discussion on Discord:

From @TrueDoctor:
> I would favor reverting most of #230 but keeping the deprecation of our fork

**Pull request merged**
