### PR TITLE
Implement bounding box for selected layers

### LINKED ISSUE #207: Select Tool: Add a bounding box around the selected layers
We can do this temporarily with the "working layers" system before we have the proper overlays system post-0.1. This clarifies to the user which shapes are actually selected.

### PR DESCRIPTION
**Pull request by TrueDoctor**
Closes #207
Reimplementation of #346

---
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/349)

### CODE REVIEW

**Review by AyeTbk — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Keavon)

___
*[editor/src/document/document_file.rs, line 371 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4OV1k12YVig6SYKkB:-Mh4OV1k12YVig6SYKkC:bnvox75) ([raw file](https://github.com/graphiteeditor/graphite/blob/28aa6a780202806ff55139d98dac7d89be3cbc5f/editor/src/document/document_file.rs#L371)):*
> ```XML
> 			}
> 			SelectAllLayers => {
> 				let all_layer_paths = self.layer_data.keys().filter(|path| !path.is_empty()).cloned().collect::<Vec<_>>();
> ```

Does this runs the risk of selecting the bounding box layer? It could cause problem if the user then pressed 'Delete' or something like that.
___
*[editor/src/tool/tools/select.rs, line 180 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4STzn-9aMUKOAaj3W:-Mh4STzn-9aMUKOAaj3X:b-r5lz03) ([raw file](https://github.com/graphiteeditor/graphite/blob/28aa6a780202806ff55139d98dac7d89be3cbc5f/editor/src/tool/tools/select.rs#L180)):*
> ```
> 					let start = data.drag_start;
> 					let size = data.drag_current - start;
> ```

Keavon wanted the start and size to be adjusted so the bounding box is "pixel perfect".
>```
>					let half_pixel_offset = DVec2::new(0.5, 0.5);
>					let start = data.drag_start.as_f64() + half_pixel_offset;
>					let size = data.drag_current.as_f64() - start + half_pixel_offset;
>```

**Review by AyeTbk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/349)* status: all files reviewed, 2 unresolved discussions (waiting on @Keavon and @TrueDoctor)

___
*[editor/src/tool/tools/select.rs, line 143 at r3](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4YNaO4Ie81fjl7EK-:-Mh4YNaO4Ie81fjl7EK0:b-5iy67t) ([raw file](https://github.com/graphiteeditor/graphite/blob/bf3e8dd17aad709616c1b8e1d2c1b236e7d5ba37/editor/src/tool/tools/select.rs#L143)):*
> ```XML
> 					let mut selected: Vec<_> = document.selected_layers().cloned().collect();
> 					let quad = data.selection_quad();
> 					let intersection = document.document.intersects_quad_root(quad);
> ```

Is anything in place to prevent the bounding boxes from being included in the intersection?
___
*[editor/src/tool/tools/select.rs, line 194 at r3](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4YrjP4W-U51UU9NSH:-Mh4YrjP4W-U51UU9NSI:b-5iy67t) ([raw file](https://github.com/graphiteeditor/graphite/blob/bf3e8dd17aad709616c1b8e1d2c1b236e7d5ba37/editor/src/tool/tools/select.rs#L194)):*
> ```XML
> 				(DrawingBox, DragStop) => {
> 					let quad = data.selection_quad();
> 					responses.push_back(DocumentMessage::SelectLayers(document.document.intersects_quad_root(quad)).into());
> ```

Is anything in place to prevent the bounding boxes from being included in the intersection?

**Review by TrueDoctor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/349)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @AyeTbk and @Keavon)

___
*[editor/src/document/document_file.rs, line 371 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4OV1k12YVig6SYKkB:-MhXH0oh1SUAk5cGfRSK:bxy3b3x) ([raw file](https://github.com/graphiteeditor/graphite/blob/28aa6a780202806ff55139d98dac7d89be3cbc5f/editor/src/document/document_file.rs#L371)):*
<details><summary><i>Previously, AyeTbk (Simon Desloges) wrote…</i></summary><blockquote>

Does this runs the risk of selecting the bounding box layer? It could cause problem if the user then pressed 'Delete' or something like that.
</blockquote></details>

Should have fixed that 
___
*[editor/src/tool/tools/select.rs, line 143 at r3](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4YNaO4Ie81fjl7EK-:-MhXGuNn5ntsgImDYEqq:b-hkdmfb) ([raw file](https://github.com/graphiteeditor/graphite/blob/bf3e8dd17aad709616c1b8e1d2c1b236e7d5ba37/editor/src/tool/tools/select.rs#L143)):*
<details><summary><i>Previously, AyeTbk (Simon Desloges) wrote…</i></summary><blockquote>

Is anything in place to prevent the bounding boxes from being included in the intersection?
</blockquote></details>

added a check for overlays in the intersect function
___
*[editor/src/tool/tools/select.rs, line 194 at r3](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4YrjP4W-U51UU9NSH:-MhXGKmgE0ovNW8e07eU:b-y7z11x) ([raw file](https://github.com/graphiteeditor/graphite/blob/bf3e8dd17aad709616c1b8e1d2c1b236e7d5ba37/editor/src/tool/tools/select.rs#L194)):*
<details><summary><i>Previously, AyeTbk (Simon Desloges) wrote…</i></summary><blockquote>

Is anything in place to prevent the bounding boxes from being included in the intersection?
</blockquote></details>

There never is a bounding box visible in this state

**Review by TrueDoctor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/349)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @AyeTbk and @Keavon)

___
*[editor/src/tool/tools/select.rs, line 194 at r3](https://reviewable.io/reviews/graphiteeditor/graphite/349#-Mh4YrjP4W-U51UU9NSH:-MhXHS1k5r1fgje7kAtF:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/bf3e8dd17aad709616c1b8e1d2c1b236e7d5ba37/editor/src/tool/tools/select.rs#L194)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

There never is a bounding box visible in this state
</blockquote></details>

Done.

**Review by Keavon — APPROVED** [review]

**Pull request merged**
