### PR TITLE
Reimplement Brightness/Contrast node using the Curves node to reduce code

### LINKED ISSUE #1387: Change Brightness/Contrast node implementation to reuse Curves node
Brightness/Contrast and Curves repeat a lot of code. This cleanup involves changing the Brightness/Contrast node so it acts as a document node wrapping the Brightness/Contrast node whilst providing it the necessary input parameters. Care should be taken to ensure that all unit tests pass with `cargo test`.

### PR DESCRIPTION
**Pull request by jafriyie1**
Closes #1387

### CODE REVIEW

**Comment by jafriyie1** [comment]
@Keavon I ran `cargo test` and the tests passed. I think this is good to go whenever you are ready!

**Review by 0HyperCube — APPROVED** [review]
Looks good

**Comment by jafriyie1** [comment]
Great thanks @0HyperCube for the review! It looks like the pull request step is failing in the Github Actions related to the Build Graphite Web step. Is there something else that I need to here? Thanks! 

For context here is part of the error message: 
```2023-10-30 14:26:43.974824272 +00:00:00 [WARN] failed to request license information from clearly defined: error sending request for url (https://api.clearlydefined.io/definitions): operation timed out
2023-10-30 14:26:43.974993965 +00:00:00 [WARN] failed to request license information from clearly defined: error sending request for url (https://api.clearlydefined.io/definitions): operation timed out
2023-10-30 14:26:43.975018431 +00:00:00 [WARN] failed to request license information from clearly defined: error sending request for url (https://api.clearlydefined.io/definitions): operation timed out

Could not run `cargo about`, which is required to generate license information.
To install cargo-about on your system, you can run `cargo install cargo-about`.
License information is required on production builds. Aborting.

> print-building-help
> echo 'Graphite project failed to build. Did you remember to `npm install` the dependencies in `/frontend`?'

Graphite project failed to build. Did you remember to `npm install` the dependencies in `/frontend`?```

**Comment by Keavon** [comment]
As long as you've run the tests which your code influences, you're good. There are other tests in our CI pipeline that is currently failing after we decided to merge a giant refactor before we could fix its tests (not usually desired, but it was needed in this case).

**Comment by Keavon** [comment]
Hi @jafriyie1, thanks again for this code contribution to the project! We're still hoping you will respond to the request to relicense this code. Please see #4208 ASAP, thank you!

**Comment by Keavon** [comment]
Hi @jafriyie1, we're grateful of your past code contribution to Graphite, but unless we hear from you by the **end of this weekend** with agreement about relicensing your code to include the MIT license, we will begin steps to remove your code contributions **so that you will no longer be a Graphite code contributor**. We'd much rather avoid this outcome, so please respond now.

To agree, simply log into your GitHub account, visit https://github.com/GraphiteEditor/Graphite/pull/4208, and copy-paste this into a comment:

"I license my past and future contributions to Graphite under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option."

If you're hesitant because you disagree or have questions, feel free to respond with another message; we'll do our best to answer your questions or concerns. More explanation is at the top of the linked thread if you're confused. **So far, 164 contributors have agreed and you are among the 11% remaining** whom we are still hoping to hear from before we begin removing your code from the project starting this Monday. (If you only see this later than Monday, your future belated response will still be appreciated.)

Thank you for your cooperation and support of open source, and we hope you'll help us keep your valued contributions in-tact.

**Pull request merged**
