### PR TITLE
Layer and grid snapping systems

### LINKED ISSUE #318: Grid snapping system
We will want a grid system for snapping.

Longer-term, here are some further features that will encompass the full grid system:

> It should also be displayed over the canvas in user-configurable ways.
> 
> We'll want a concept of document pixels for precise pixel alignment and snapping, drawing pixel art, and previewing a zoomed-in document at its export resolution. (Even though this concept exists for measurements, it does not restrict the rendering of the document at any arbitrarily high resolution, because of Graphite's concept of resolution agnosticism.)
> 
> We will want both pixel and real-world (metric/US) units of measure at arbitrarily large or small scales (millimeters to miles, or even way smaller and larger): #586 
> 
> This suite of grid-related features will live under the Grid checkbox's popover menu. Disabling the checkbox will turn off all rendering of grids. The popover dropdown next to the checkbox allows selectively enabling and disabling specific grid rendering features and changing certain settings like lines or dots for the grid style, the resolution of the grid (based on a chosen unit of measurement, either pixels or real-world units), and even setting the grid to work based on polar coordinates or logarithmic scales in the future.

For the MVP grid snapping, we want:

- [x] Hook up the grid button in the options bar of the document to enable and disable all grid features
- [x] Transforming a layer or point, such as dragging, grabbing (the <kbd>G</kbd> of G/R/S), nudging, etc., should snap (round) it to the nearest integer in document coordinates

### LINKED ISSUE #633: Snapping to vector edges/curves
Currently we can snap to points. It'd be great to snap along an edge/curve of another vector shape. This might be a little tricky on the math side of things.

### LINKED ISSUE #1206: Layer-to-layer snapping system
Probably base it on inkscape's snapping!

### PR DESCRIPTION
**Pull request by 0HyperCube**
Closes #1206 closes #318 closes #633

Functionality
- [x] Free snapping
- [x] Contrained snapping (e.g. drag on one axis with select, or constrained aspect ratio with rectangle tool)

Tools
- [x] Select
- [x] Path
- [x] Pen
- [x] Line
- [x] Rect
- [x] Circle
- [x] Shape

Bounds snapping
- [x] edges
- [x] corners
- [x] edge midpoints
- [x] centres
- [x] overlays

Node snapping
- [x] paths
- [x] path_intersections
- [x] cusp_nodes
- [x] smooth_nodes
- [x] line midpoints
- [x] normals
- [x] tangents
- [x] overlays

Grid snapping
- [x] to line
- [x] to intersections
- [x] overlays
- [x] Customise offset and size
- [x] isometric grid

### CODE REVIEW

**Comment by otdavies** [comment]
Going to zero or negative spacing seems to cause an editor freeze.

**Comment by otdavies** [comment]
Another note:

Looks like in certain situations while scaling there is a jumpy / jittery behavior here.
Example:
https://github.com/GraphiteEditor/Graphite/assets/3145170/31f2cb9b-102d-4212-9797-8e1d7ece408a

File (remove the .json): [example.graphite.json](https://github.com/GraphiteEditor/Graphite/files/13909985/example.graphite.json)

**Comment by 0HyperCube** [comment]
> Note: Going to zero or negative spacing seems to cause an editor freeze.

Fixed @otdavies 

> Looks like in certain situations while scaling there is a jumpy / jittery behavior while snapping..

This was caused by a NaN being produced when calculating the X distance. I added a check to avoid this and fix the behaviour.

**Review by Keavon — APPROVED** [review]
Freakin' amazing!

**Pull request merged**
