### PR TITLE
Fix doubled translation from dragging layers sharing an upstream Transform node

### LINKED ISSUE #1529: Dragging layers sharing a transform node applies multiple translations
Create a document containing two rectangles. Enter the node graph and add a layer node, using the data from the stroke node of one of the rectangles. Select all of the rectangles and drag them using the select tool. Observe how the translation is applied several times. When you drag around several layers we apply a transformation to the first transform node found for each layer; however because there are several layers sharing the same transform node, the translation is applied several times.

Solutions:
- In select_tool.rs, instead of applying a delta to the current transform, store the transform at the start of the drag and compute the new transform based on that (similar to how dragging the selection bounds works)
- In graph_operation_message_handler.rs, check for cases where the node is used by several other nodes, and if that is the case then create a new transform node for each layer separately before applying the operation.

https://github.com/GraphiteEditor/Graphite/assets/78500760/8011ef59-a055-4e29-87a8-9df5d73351e6

### PR DESCRIPTION
**Pull request by shipp02**
Hello,

This fixes above issue, demo:

https://github.com/GraphiteEditor/Graphite/assets/51503822/70b7fccb-8520-45d5-a599-0b4f8ce24ecf

Closes #1529

### CODE REVIEW

**Comment by Keavon** [comment]
@0HyperCube you're better than me at understanding this part of the code and the implications of this change. Could you please see if this looks good to go? Thanks.

**Comment by Keavon** [comment]
@shipp02 please leave a comment in the original issue so I can assign it to you.

**Comment by Keavon** [comment]
I finally got a chance to do some QA testing on this. The first thing I noticed is that Dragging individual layers is completely broken. Just draw two layers and try dragging each of them on after the other. This is probably caused by your choice to store the transform in the Select tool's struct. I'd avoid attempting to persist state since this should be a stateless problem as far as I can tell.

**Comment by 0HyperCube** [comment]
@Keavon persisting state is necessary to implement the first of my suggested solutions from the issue:
> In select_tool.rs, instead of applying a delta to the current transform, store the transform at the start of the drag and compute the new transform based on that (similar to how dragging the selection bounds works)

**Comment by shipp02** [comment]
Thank you for confirming my approach!

 I was in the middle of finals hence the lack of a response from me in the
last week.

I will fix the bug @Keavon found while he was running QA.

**Comment by Keavon** [comment]
@shipp02 just checking if you've been able to continue addressing this.

**Comment by shipp02** [comment]
I was able to reproduce the regression you mentioned but wasn't sure how to fix it.

**Comment by Keavon** [comment]
I'm going to close this for now but feel free to reopen it if you're able to continue making progress.

**Pull request closed without merging**
