### PR TITLE
Fix the spline node algorithm to be continuous across start/end points

### LINKED ISSUE #2086: Fix the spline node algorithm to be continuous across start/end points
Currently, the Spline from Points node doesn't handle continuity across the start/end point portion of the edge flow. This is what a square looks like when the node is applied, which fails in the top left corner where the start/end points connect:

capture

Instead, this example should look like a symmetrical blob, with the same roundness around all corners.

This task involves updating the spline calculation algorithm, as pointed out by [this todo comment](https://github.com/GraphiteEditor/Graphite/commit/3f17e83e80d345a373f0df07ed642fc95de871e2#diff-e7a79f7e09ecb50a47584450e9b37dda9b437bbf0dbda93360c8ad1cdb8445c0R955).

### PR DESCRIPTION
**Pull request by 0HyperCube**
Closes #2086

### CODE REVIEW

**Comment by Keavon** [comment]
It doesn't look like this is producing the expected results.

Input:
capture

Dev:
capture

This PR:
capture

**Comment by Keavon** [comment]
Understood, and yes, if you're offering to do that improvement here too, that's probably the most expedient option to move forward. Thank you!

**Comment by 0HyperCube** [comment]
@Keavon I have implemented the new algorithm here. I have also added a test to confirm that the second derivative is continuous across all adjacent pairs of segments.

**Review by Keavon — APPROVED** [review]
Super! Love the much cleaner code, and the solved continuous closed subpath solution. I can finally use this node in my Nodevember creations now that it doesn't have a random sharp point 😀

**Pull request merged**
