### PR TITLE
Properly handle pen tool undo and redo

### PR DESCRIPTION
**Pull request by zhiyuang**
Closes https://github.com/GraphiteEditor/Graphite/issues/971

refer to Figma

### CODE REVIEW

**Comment by 0HyperCube** [comment]
!build

**Comment by Keavon** [comment]
This is a phenomenal improvement that was much needed! I spent 30 seconds testing it but I'll do a closer look tomorrow. I should hopefully get to reviewing both of your PRs tomorrow (I've been rather consumed by some code I've been working on which has been where all my attention has gone this past week).

**Review by 0HyperCube — APPROVED** [review]
Thanks for this great improvement - the code looks good.

From a UX perspective I'm not sure how we want to deal with undo after drawing a complete path and confirming. Inkscape deletes the whole path. Figma switches back to the pen tool and does undo point by point. This PR currently just does undo point by point without selecting the path tool.

**Comment by Keavon** [comment]
I'm also unsure. I was slightly surprised when it happened while I was testing it since that's not what I'm used to, but when I thought about it, I realized that might actually be desired. I'd suggest we merge as-is and think about the UX more over time and take into consideration the pros/cons throughout its usage and any potential future user feedback.

**Pull request merged**
