### PR TITLE
Clear artboard

### PR DESCRIPTION
**Pull request by moOsama76**

### CODE REVIEW

**Comment by moOsama76** [comment]
Note that merge nodes are named "Artboard" as I reserve the name

**Comment by Keavon** [comment]
!build

**Comment by adamgerhant** [comment]
I would like to see the artboards name/position/downstream connnector/upstream connectors being saved, then the artboard is deleted, a layer node is created,  its name/position are set, then it is reconnecting. All using the same functions in the network interface as if the user was to do with.

Also, make sure to start and end a transaction at the start and end of the message. Its also important that no mutable network interface functions are called in a message that has a start/end transaction.

It would also be nice if the artboards position is then used to set the transform of the new layer, so that the contents stay at the same place. This would require using a monitor node to access the artboard data, where the translation is stored.

**Comment by Keavon** [comment]
I'll mark this as a draft until those comments are addressed. Thanks for taking the time to review this, @adamgerhant.

**Comment by adamgerhant** [comment]
You can use however many loops are necessary to achieve the correct behavior

**Comment by moOsama76** [comment]
> Just checking in on the status of this @moOsama76.

I was taking a break, will do it this week

**Comment by Keavon** [comment]
I'll close this PR for now, but please feel free to reopen it once you've addressed the code review feedback from Adam.

**Comment by moOsama76** [comment]
> I'll close this PR for now, but please feel free to reopen it once you've addressed the code review feedback from Adam.

No problem I am getting back soon I promise :)

**Pull request closed without merging**
