### PR TITLE
Experimental Overlay renderer

### PR DESCRIPTION
**Pull request by TrueDoctor**
Closes #

### CODE REVIEW

**Comment by Keavon** [comment]
In this branch, didn't you do something with the event system to speed up overlay rendering? Could you please backport that to master?

**Comment by TrueDoctor** [comment]
> In this branch, didn't you do something with the event system to speed up overlay rendering? Could you please backport that to master?

I did two changes, the first one was to use the message deduplicaton provided by the messaging system, the other one was to switch to using request animation frame.
The first one should be relatively easy to backport: https://github.com/GraphiteEditor/Graphite/pull/522/commits/2ba44922e10a0f196b29b81631a1c7bd5d39e06a

**Comment by Keavon** [comment]
If you could make a PR for that when you get the chance, that would be splendid.

**Comment by TrueDoctor** [comment]
> If you could make a PR for that when you get the chance, that would be splendid.

Just checkd, the first option was already fixed in https://github.com/GraphiteEditor/Graphite/pull/522#issuecomment-1105763627
the other performance improvements are non trivial. We could try to use lyon to triangulate the overlays because I had a few issues with the sdf approach in regards to non rounded corners and blending

**Comment by Keavon** [comment]
Closing this for now but keeping the branch around.

**Pull request closed without merging**
