### PR TITLE
Selection history navigation with Alt+[ and Alt+] keys should filter out empty selections

### PR DESCRIPTION
**Pull request by 0SlowPoke0**
filters empty selections made by select tool  before adding in the selection history

### CODE REVIEW

**Comment by 0HyperCube** [comment]
!build

**Review by 0HyperCube — APPROVED** [review]
Thanks for this fix; it appears to work as expected (although perhaps @Keavon will want to check as well).

**Comment by Keavon** [comment]
@0SlowPoke0 @0HyperCube can you both please confirm that my simplification commit c362e26f97b4d21f40bbcf5e05b47dd126d2a81d is indeed equivalent? I don't understand why it was so complicated before, and I'm pretty sure the changes I made are correct, but I'm asking to make sure I didn't miss any subtleties that explained why the previous code was so complicated.

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
This PR breaks the editor (unable to draw more shapes, unable to select layers, etc.) after you've drawn the first shape.

**Comment by Keavon** [comment]
!build

**Comment by 0SlowPoke0** [comment]
@Keavon  I think this solves the issue can you please review the build, thanks.

**Comment by Keavon** [comment]
Superseded by #2138

**Pull request closed without merging**
