### PR TITLE
🎨 Add colours in Rust

### PR DESCRIPTION
**Pull request by 0HyperCube**
🎨 Add colours in Rust. I had to do quite a lot of refactoring.

I'm sorry I had the refactoring in the same commit, I should probably commit more often.

---
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)

### CODE REVIEW

**Comment by TrueDoctor** [comment]
Having the file split in the same commit as the rest makes it a lot harder to review, but I guess we have to live with that

**Review by TrueDoctor — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: all files reviewed, 6 unresolved discussions (waiting on @0HyperCube)

___
*[core/document/src/layers/circle.rs, line 4 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkVd_13AQkYqQ-ZNFl:-MYkVd_29BrwzaHTDte8:blfqog6) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/circle.rs#L4)):*
> ```XML
> use super::LayerData;
> 
> #[derive(Debug, Clone, Copy, PartialEq)]
> ```

Consider deriving a default impl for easier internal use
___
*[core/document/src/layers/layer_props/mod.rs, line 3 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYklTVACFwqKHn4PmnV:-MYklTVB2afINQKLsQaa:bw07tfe) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/layer_props/mod.rs#L3)):*
> ```XML
> use crate::color::Color;
> 
> #[derive(Debug, Clone, Copy, PartialEq)]
> ```

consider adding repr(C) to allow for ffi
___
*[core/document/src/layers/layer_props/mod.rs, line 4 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYknEokCNFRGd6wCJvh:-MYknEokCNFRGd6wCJvi:b-hhptre) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/layer_props/mod.rs#L4)):*
> ```XML
> 
> #[derive(Debug, Clone, Copy, PartialEq)]
> pub enum Fill {
> ```

why None() and not None?
and shouldn't we just use an option?
___
*[core/document/src/layers/layer_props/mod.rs, line 20 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkl_106rRN6IXm7-eR:-MYkl_106rRN6IXm7-eS:bw07tfe) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/layer_props/mod.rs#L20)):*
> ```XML
> }
> 
> #[derive(Debug, Clone, Copy, PartialEq)]
> ```

consider adding repr(C) to allow for ffi
___
*[core/editor/src/dispatcher/events.rs, line 3 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkliyL4M7CoFenTALw:-MYkliyL4M7CoFenTALx:b-xyz337) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/editor/src/dispatcher/events.rs#L3)):*
> ```XML
> use crate::tools::ToolType;
> use bitflags::bitflags;
> use document_core::color::Color;
> ```

This should not be necessary because Color is reexported in the crate root
___
*[core/document/src/color.rs, line 57 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkU7aj5kZoHZ3UIRT0:-MYkU7aj5kZoHZ3UIRT1:b-irhzef) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L57)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 		format!(
> 			"{:02X?}{:02X?}{:02X?}{:02X?}",
> 			(self.r() * 255.) as u8,
> 			(self.g() * 255.) as u8,
> 			(self.b() * 255.) as u8,
> 			(self.a() * 255.) as u8,
> ```
</details>

colors values are not guaranteed to be in the range from [0.0, 1.0] this might cause the code to panic upon conversion

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 18 of 29 files reviewed, 6 unresolved discussions (waiting on @TrueDoctor)

___
*[core/document/src/layers/circle.rs, line 4 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkVd_13AQkYqQ-ZNFl:-MYkyQi124jmiysBkJrk:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/circle.rs#L4)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

Consider deriving a default impl for easier internal use
</blockquote></details>

Done.
___
*[core/document/src/layers/layer_props/mod.rs, line 3 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYklTVACFwqKHn4PmnV:-MYkyNZz3b8tk4ApoqZq:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/layer_props/mod.rs#L3)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

consider adding repr(C) to allow for ffi
</blockquote></details>

Done.
___
*[core/document/src/layers/layer_props/mod.rs, line 4 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYknEokCNFRGd6wCJvh:-MYkyO2WEk1hDEn45n5F:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/layer_props/mod.rs#L4)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

why None() and not None?
and shouldn't we just use an option?
</blockquote></details>

Done.
___
*[core/document/src/layers/layer_props/mod.rs, line 20 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkl_106rRN6IXm7-eR:-MYkyOhrDUSnBfHarkMG:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/layers/layer_props/mod.rs#L20)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

consider adding repr(C) to allow for ffi
</blockquote></details>

Done.
___
*[core/editor/src/dispatcher/events.rs, line 3 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkliyL4M7CoFenTALw:-MYkohBQ56tYXZyQ5mKb:b-yxgl2d) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/editor/src/dispatcher/events.rs#L3)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

This should not be necessary because Color is reexported in the crate root
</blockquote></details>

Ok. What should I change it to. It doesn't work with `use color::Color;` or with removing it completely (sorry I'm still quite new to Rust's module system)
___
*[core/document/src/color.rs, line 57 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkU7aj5kZoHZ3UIRT0:-MYkq6cZ1LBbeE7j88-E:b2w9rtt) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L57)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

> ```
> 		format!(
> 			"{:02X?}{:02X?}{:02X?}{:02X?}",
> 			(self.r() * 255.) as u8,
> 			(self.g() * 255.) as u8,
> 			(self.b() * 255.) as u8,
> 			(self.a() * 255.) as u8,
> ```
colors values are not guaranteed to be in the range from [0.0, 1.0] this might cause the code to panic upon conversion
</blockquote></details>

Ok. Shouldn't this be handled when the colour is initialised or do I need to do a check?

**Review by TrueDoctor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 18 of 29 files reviewed, 4 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[core/editor/src/dispatcher/events.rs, line 3 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkliyL4M7CoFenTALw:-MYl4mTfBVIW_1uOvKjN:bkhzx7i) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/editor/src/dispatcher/events.rs#L3)):*
<details><summary><i>Previously, 0HyperCube wrote…</i></summary><blockquote>

Ok. What should I change it to. It doesn't work with `use color::Color;` or with removing it completely (sorry I'm still quite new to Rust's module system)
</blockquote></details>

use crate::Color
___
*[core/document/src/color.rs, line 57 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkU7aj5kZoHZ3UIRT0:-MYl4BRx3pz_KhsDRrlH:b-vwscte) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L57)):*
<details><summary><i>Previously, 0HyperCube wrote…</i></summary><blockquote>

Ok. Shouldn't this be handled when the colour is initialised or do I need to do a check?
</blockquote></details>

With the current color design we don't limit colors to that range, complain to @keavon about it :P

**Review by Keavon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 18 of 29 files reviewed, 6 unresolved discussions (waiting on @0HyperCube and @TrueDoctor)

___
*[client/web/wasm/Cargo.toml, line 21 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl85WWCKB-_mZE-cCq:-MYl85WWCKB-_mZE-cCr:b-hm14oi) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/client/web/wasm/Cargo.toml#L21)):*
> ```TOML
> console_error_panic_hook = { version = "0.1.6", optional = true }
> editor-core = { path = "../../../core/editor", package = "graphite-editor-core" }
> document-core = { path = "../../../core/document", package = "graphite-document-core" }
> ```

Can we avoid this? I think it would best fit the architecture if we can cleanly keep the frontend only aware of the Editor Core Library. Maybe we can do some re-exports like with Color? @truedoctor , thoughts?
___
*[core/document/src/operation.rs, line 10 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl6-EWA0lM0wRcpxZ9:-MYl6-EWA0lM0wRcpxZA:b-3m6u66) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/core/document/src/operation.rs#L10)):*
> ```XML
> 		cy: f64,
> 		r: f64,
> 		stroke: Option<layer_props::Stroke>,
> ```

Can we wrap `stroke` and `fill` in a `styling` struct, which has `stroke` and `fill` as optional parameters?
___
*[core/editor/src/tools/mod.rs, line 15 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl7TTBB5Ef5k3zst4L:-MYl7TTC53lHMhO8B7ty:brx1tc1) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/core/editor/src/tools/mod.rs#L15)):*
> ```XML
> use crate::Document;
> use crate::EditorError;
> use document_core::{color::Color, Operation};
> ```

Do we want to change `crate::Color` to `color::Color`?
___
*[core/document/src/color.rs, line 17 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkotCQB8x4doxZfpCG:-MYkotCQB8x4doxZfpCH:b-uaoah5) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L17)):*
> ```XML
> 	pub const BLUE: Color = Color::from_unsafe(0., 0., 1.);
> 
> 	pub fn from_rgbaf32(red: f32, green: f32, blue: f32, alpha: f32) -> Option<Color> {
> ```

What's the reasoning behind changing this from an `Option` to a `Result`?
___
*[core/document/src/color.rs, line 57 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkU7aj5kZoHZ3UIRT0:-MYkpCO4E5zYe5ARaI6e:blnjo9p) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L57)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

> ```
> 		format!(
> 			"{:02X?}{:02X?}{:02X?}{:02X?}",
> 			(self.r() * 255.) as u8,
> 			(self.g() * 255.) as u8,
> 			(self.b() * 255.) as u8,
> 			(self.a() * 255.) as u8,
> ```
colors values are not guaranteed to be in the range from [0.0, 1.0] this might cause the code to panic upon conversion
</blockquote></details>

Yeah, we need to check for that and, if it's outside the standard 24-bit hex color range, provide either a string like "color is not hex" or an empty string, or wrap this in a `Result` which might be the best solution.

**Review by TrueDoctor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 18 of 29 files reviewed, 6 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[core/editor/src/tools/mod.rs, line 15 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl7TTBB5Ef5k3zst4L:-MYlAZNt0aiigh0LiZe4:b-a1ish9) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/core/editor/src/tools/mod.rs#L15)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Do we want to change `crate::Color` to `color::Color`?
</blockquote></details>

would not work because Color is a reexport
___
*[core/document/src/color.rs, line 17 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkotCQB8x4doxZfpCG:-MYlAQ9J7nKz5-khbfed:b-e4t09) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L17)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

What's the reasoning behind changing this from an `Option` to a `Result`?
</blockquote></details>

because we don't have the result available in the doc crate

**Review by Keavon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 18 of 29 files reviewed, 6 unresolved discussions (waiting on @0HyperCube and @TrueDoctor)

___
*[core/editor/src/tools/mod.rs, line 15 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl7TTBB5Ef5k3zst4L:-MYlBueEElkmiXDwUWyh:bt84tl5) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/core/editor/src/tools/mod.rs#L15)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

would not work because Color is a reexport
</blockquote></details>

Sorry, I may have worded that unclearly, let me know if this rewording changes your understanding and your reply:

Is there a reason we needed to change `crate::Color` to change to `color::Color`?
___
*[core/document/src/color.rs, line 17 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkotCQB8x4doxZfpCG:-MYlCLAe0vDqYgvc-mhj:bs4huf1) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L17)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

because we don't have the result available in the doc crate
</blockquote></details>

I'm not sure I understand what you mean, but if you agree it's necessary that sounds good to me.

**Review by TrueDoctor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 18 of 29 files reviewed, 6 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[client/web/wasm/Cargo.toml, line 21 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl85WWCKB-_mZE-cCq:-MYlCTZU6vBa3H-VbSE2:bmnnt0z) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/client/web/wasm/Cargo.toml#L21)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Can we avoid this? I think it would best fit the architecture if we can cleanly keep the frontend only aware of the Editor Core Library. Maybe we can do some re-exports like with Color? @truedoctor , thoughts?
</blockquote></details>

Yes, we should be able to wrap everything in reexports
___
*[core/editor/src/tools/mod.rs, line 15 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl7TTBB5Ef5k3zst4L:-MYlCzQR0g9KX6bfo7vx:buy3nb4) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/core/editor/src/tools/mod.rs#L15)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Sorry, I may have worded that unclearly, let me know if this rewording changes your understanding and your reply:

Is there a reason we needed to change `crate::Color` to change to `color::Color`?
</blockquote></details>

I'd argue for using crate:Color
___
*[core/document/src/color.rs, line 17 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkotCQB8x4doxZfpCG:-MYlCftFDRdX6GQ-y_xY:b-aeylwl) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/document/src/color.rs#L17)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

I'm not sure I understand what you mean, but if you agree it's necessary that sounds good to me.
</blockquote></details>

We cant use the editor error to avoid circular deps, but we can use a result

**Review by TrueDoctor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 18 of 29 files reviewed, 6 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[core/editor/src/dispatcher/events.rs, line 3 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYkliyL4M7CoFenTALw:-MYmzOAq5dYLIpmI4_IV:bhymkwb) ([raw file](https://github.com/graphiteeditor/graphite/blob/631817ad162e5cfd89777a920eceb3a8d35d734f/core/editor/src/dispatcher/events.rs#L3)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

use crate::Color
</blockquote></details>

color::Color does not work, because the color module does not exist in the editor crate, but we can use the reexported Color without having to explicitly specify document. This is helpful if we want to change the color implementation used and don't have to change every import, creating less noise

**Review by TrueDoctor — COMMENTED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: all files reviewed, 6 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

**Review by TrueDoctor — COMMENTED** [review]
> Reviewed 14 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: 28 of 29 files reviewed, 5 unresolved discussions (waiting on @0HyperCube, @Keavon, and @TrueDoctor)

___
*[client/web/wasm/Cargo.toml, line 21 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/78#-MYl85WWCKB-_mZE-cCq:-MYpvpvC629BguUD0Clg:bb6un1j) ([raw file](https://github.com/graphiteeditor/graphite/blob/b26f717f4692a4d1becca61ef7759da1b36de787/client/web/wasm/Cargo.toml#L21)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

Yes, we should be able to wrap everything in reexports
</blockquote></details>

Done

**Review by TrueDoctor — APPROVED** [review]
> Reviewed 1 of 15 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: all files reviewed, 4 unresolved discussions (waiting on @0HyperCube and @Keavon)

**Review by Keavon — APPROVED** [review]
> Reviewed 11 of 29 files at r1, 1 of 11 files at r2, 15 of 15 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0HyperCube)

**Review by TrueDoctor — APPROVED** [review]
> Reviewed 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @0HyperCube)

**Pull request merged**
