### PR TITLE
Rename and organize widget components to conform to design terminology

### PR DESCRIPTION
**Pull request by Keavon**
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/132)

### CODE REVIEW

**Comment by Keavon** [comment]
To be merged AFTER #131.

**Review by TrueDoctor — COMMENTED** [review]
The popover "hitbox" changes based on the browser scale. It moves downwards when zooming in and moves upwards when zooming out

> Reviewed 16 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/132#-:-MaFO7aE3QOVNF3ApKMK:bblkmml)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @Keavon)

**Review by TrueDoctor — APPROVED** [review]
But I guess we can fix that together with the misalignment of the arrows in a follow up pr

> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/132#-:-MaFRzty0QoTBwfSEd3I:buu7zir)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @Keavon)

**Comment by Keavon** [comment]
Please file a bug. I'm also not sure what the second bug is you mentioned, with the misaligned arrows.

**Comment by TrueDoctor** [comment]
Just checked, the arrow this is not really important, the alignment seems to be half a pixel off but that might be some anti aliasing artifact. Will file a bug report for the other thing

**Pull request merged**
