### PR TITLE
implemented left selection logic

### LINKED ISSUE #2041: Selection direction difference
The selection direction should make a difference.
Usually in apps like these if you start a selection frame by dragging the mouse to the right it should only select objects that are fully inside of the selection frame. If the user drags to the left everything that is _touched_ by the selection frame should be selected.

### PR DESCRIPTION
**Pull request by pratikagr**
Fixes #2041  
1. Added logic to calculate the drag direction (left or right) using `calculate_direction`.
2. Integrated the `intersect_quad_no_artboards` function for leftward drags to select all intersecting objects.
3. Updated the selection process to differentiate between leftward (intersects).
4. Rightward drag is yet to be implemented. i am working on it.

### CODE REVIEW

**Comment by Keavon** [comment]
Hello, could you please link to which issue this pertains to? Based on your description, I'm not familiar with what this aims to implement.

**Comment by pratikagr** [comment]
> Hello, could you please link to which issue this pertains to? Based on your description, I'm not familiar with what this aims to implement.

My bad, this PR addresses issue #2041

**Comment by Keavon** [comment]
Please be sure to include that in the original PR description.

**Comment by 0HyperCube** [comment]
@pratikagr I have marked as a draft since the functionality isn't implemented.

**Comment by Keavon** [comment]
Closing this, but feel free to reopen if it is revisited.

**Pull request closed without merging**
