### PR TITLE
Add Pan/Tilt/Zoom to View menu; change Tilt shortcut

### LINKED ISSUE #1352: Dropdown button for rotating camera
Currently the viewport can be rotated by holding <kbd>Ctrl</kbd> whilst dragging with the middle mouse button. This is however difficult to find. A similar option should be added to the menu bar at the top of the app, in the view menu to rotate the canvas.

The code for the menu bar can be found in `editor/src/messages/portfolio/menu_bar/menu_bar_message_handler.rs:250`.
The code for the canvas rotation can be found in `editor/src/messages/portfolio/document/navigation/navigation_message_handler.rs:197`.

Inspiration can be taken from similar views in inkscape and illustrator 
inkscape camera orientation dropdownillustrator camera rotate dropdown

### LINKED ISSUE #1365: Rearrange Pan/Tilt/Zoom features for better discoverability
- Switch Ctrl+MMB to Alt+MMB for tilt from any tool
- Improve the layout of the View menu
- More (ask Keavon)

### PR DESCRIPTION
**Pull request by Ezbaze**
Closes #1352
Closes #1365

### CODE REVIEW

**Comment by TrueDoctor** [comment]
Code looks good, @Keavon can you check the behaviour?

**Comment by Keavon** [comment]
- [ ] RMB abort doesn't appear to work. We also want LMB confirm (including that being added to the hint bar).

I also got to try this iteration of the updated keys where Alt+LMB is used for tilt and I realized this conflicts with Alt+LMB interaction with the viewport layers (e.g. to duplicate the dragged shape, to resize around the center of a bounding box, etc.), so I need to devise another iteration. Here it is:

- MMB navigation family (ergonomic by only taking one modifier key, but requires the ability to MMB drag which might not be possible on all input devices like trackpads):
    - [ ] MMB drag -> pan
    - [ ] Alt+MMB drag -> tilt
    - [ ] Shift+MMB drag -> zoom
- Space+LMB navigation family (for users who can only LMB drag with their input hardware, Space is a modifier that moves the shortcuts from working with MMB to LMB without conflicting with artwork editing):
    - [ ] Space+LMB drag -> pan
    - [ ] Space+Alt+LMB drag -> tilt
    - [ ] Space+Shift+LMB drag -> zoom

Each of these keeps Ctrl available for increment snapping and RMB available for abort. Unfortunately Space+Alt+Ctrl for snapping during a tilt is unergonomic but tilting is the most rare and increment snapping during the tilt is even rarer.

We probably should display the MMB navigation family's keyboard shortcuts by default in the hint bar and View menu, not the more verbose Space+LMB accessibility mode.

Lastly, we want the Navigate tool to also fit in consistently with this scheme. As its icon shows a zoom and tilt, we don't need to technically support pan meaning that operation will be the same as its global operation, but shown in the hint bar for teaching purposes.

- Navigate tool family (which exists to provide a way to navigate without the ability to MMB or RMB drag for users who need to learn the shortcuts from the hints bar instead of using the global modes):
    - Space+LMB drag -> pan (actually just the global navigation, but shown in hints bar)
    - Alt+LMB drag -> tilt
    - Shift+LMB drag -> zoom (should also support LMB drag, without Shift, as an alias but hints should show Shift+LMB drag for learning purposes to match with the global modes)
    - LMB click -> zoom in (unique to the Navigate tool)
    - Shift+LMB click -> zoom out (unique to the Navigate tool)

**Comment by Keavon** [comment]
Switching this back to a draft for now while awaiting those comments to be addressed, thanks @Ezbaze. As always, let me know if you have questions or need any help.

**Comment by mobile-bungalow** [comment]
this should be closed as of merging #1419

**Pull request closed without merging**
