### PR TITLE
Cull snapping of points outside viewport

### PR DESCRIPTION
**Pull request by 0HyperCube**
As discussed in discord, do not snap to points outside viewport.

### CODE REVIEW

**Comment by Keavon** [comment]
Can you please make it update the list when panning (e.g. with the scroll wheel) during the drawing of a shape?

**Comment by 0HyperCube** [comment]
Panning whilst drawing does not update the snapping system, regardless of this PR @Keavon.

**Comment by Keavon** [comment]
> 

Would it be simple to add that here, or should I file a new issue to request that improvement? If the latter, feel free to merge now.

**Review by Keavon — APPROVED** [review]

**Review by Keavon — APPROVED** [review]

**Comment by Keavon** [comment]
Closes #991.

**Pull request merged**
