### PR TITLE
Microtransactions (April Fools)

### PR DESCRIPTION
**Pull request by T0mstone**
This PR implements microtransactions, a feature essential to every piece of modern software.
The implementation is only a stub for now, as we still have to figure out how to process payments

### CODE REVIEW

**Comment by TrueDoctor** [comment]
We might need to implement some sort of cryptographic verification to stop users from just modifying our memory from the js frontend

**Review by Keavon — APPROVED** [review]
Glad we are getting an early start on these important features!

**Comment by TrueDoctor** [comment]
And what do you think about a limited stroke length? That way users could still use all tools, just not for any longer than 5 cm or some amount of time

**Comment by Keavon** [comment]
We may also want to charge for either the red, green, or blue color primary. That way people can get a taste for Graphite's capabilities with 2/3 of the hue spectrum, but if they want to unlock the full capabilities of color and stop making art with stylized color palettes, a microtransaction would be required.

**Comment by T0mstone** [comment]
April 1st should be over in every time zone now

**Pull request closed without merging**
