### PR TITLE
Plumb layer panel

### PR DESCRIPTION
**Pull request by TrueDoctor**
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)

### CODE REVIEW

**Review by Keavon — CHANGES_REQUESTED** [review]
Nice work on the TypeScript. I think this is a reasonable approach even though it does rely a bit on some casting (which tells TypeScript to ignore its type checking and dangerously cast it unchecked). Seems like a reasonable tradeoff though.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107#-:-M_3WX-E-EFz71gL-m1h:b-15knti)* status: all files reviewed, 7 unresolved discussions (waiting on @TrueDoctor)

___
*[client/web/src/response-handler.ts, line 27 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3LBrRCafT_4mIzi-Q:-M_3LBrRCafT_4mIzi-R:b-3ygk60) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/response-handler.ts#L27)):*
> ```XML
> 
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> function parseResponse(origin: string, type: string, data: any): Response {
> ```

Please rename `type` to something else since `type` is technically a reserved word in TypeScript.
___
*[client/web/src/response-handler.ts, line 36 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3O_jl7E77JTovFjHl:-M_3O_jl7E77JTovFjHm:b-7eija) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/response-handler.ts#L36)):*
> ```XML
> 					return data.Document.CollapseFolder as Response;
> 				case "ExpandFolder":
> 					return (data.Document.ExpandFolder as ExpandFolder) as Response;
> ```

Shouldn't all of them have the form of `(... as TheTypesTheyAre) as Response`?
___
*[client/web/src/response-handler.ts, line 52 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3Omi65HOIl3K9tNDH:-M_3Omi743-7ZbZvR16w:b-mr6xeu) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/response-handler.ts#L52)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> export function handleResponse(responseType: ResponseType, responseData: any) {
> 	const [origin, type] = responseType.split("::", 2);
> ```

Same here about `type`.
___
*[client/web/wasm/src/document.rs, line 128 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3UzMM9ME_yTuOfWoS:-M_3UzMM9ME_yTuOfWoT:bfw9mnv) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L128)):*
> ```XML
> /// Toggle visibility of a layer from the layer list
> #[wasm_bindgen]
> pub fn toggle_layer_visibility(path: Vec<LayerId>) -> Result<(), JsValue> {
> ```

I'm wondering if toggle is a good idea, or if we should explicitly set the visibility to avoid some sort of state de-sync. Probably not an issue because only the change in the backend will actually cause an update to the rendering of the frontend. But maybe worth discussing more? Same also applies to the `toggle_layer_expansion` below.
___
*[client/web/wasm/src/document.rs, line 144 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3VRBo3ek9Z6IhOpbv:-M_3VRBo3ek9Z6IhOpbw:b-gqia92) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L144)):*
> ```XML
> ///  Renames a layer from the layer list
> #[wasm_bindgen]
> pub fn rename_layer(path: Vec<LayerId>, name: String) -> Result<(), JsValue> {
> ```

`new_name` would be preferable for clarity.
___
*[client/web/wasm/src/document.rs, line 152 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3VcbsDrWXL_akgZZ-:-M_3VcbsDrWXL_akgZZ0:b4vhhmv) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L152)):*
> ```XML
> ///  Deletes a layer from the layer list
> #[wasm_bindgen]
> pub fn delete_layer(path: Vec<LayerId>, name: String) -> Result<(), JsValue> {
> ```

Why is `name` a parameter?
___
*[client/web/wasm/src/document.rs, line 156 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3VgqL7R3TsuvmjaX_:-M_3VgqL7R3TsuvmjaXa:b-tfd9ys) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L156)):*
> ```XML
> }
> 
> ///  Deletes a layer from the layer list
> ```

Outdated comment

**Review by Keavon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: all files reviewed, 8 unresolved discussions (waiting on @TrueDoctor)

___
*[client/web/src/components/panels/LayerTree.vue, line 24 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3XIneCR8hvA5iCoYa:-M_3XIneCR8hvA5iCoYb:b-xvofgs) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/components/panels/LayerTree.vue#L24)):*
> ```Vue
> 					</div>
> 					<div class="layer-name">
> 						<span>{{layer.name}}</span>
> ```

This seems to be resulting in the name of "UnnamedFolder" even though the shapes aren't folders (is that indicative of a bug?). Is it an easy fix to make them say "Unnamed Ellipse", "Unnamed Circle", "Unnamed Line", "Unnamed Rectangle", and "Unnamed Polygon"? If not, we can add that later.

**Review by TrueDoctor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: 1 of 13 files reviewed, 8 unresolved discussions (waiting on @Keavon)

___
*[client/web/src/response-handler.ts, line 27 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3LBrRCafT_4mIzi-Q:-M_4BtBe88wK6A9Xxbo1:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/response-handler.ts#L27)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Please rename `type` to something else since `type` is technically a reserved word in TypeScript.
</blockquote></details>

Done.
___
*[client/web/src/response-handler.ts, line 36 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3O_jl7E77JTovFjHl:-M_4BvjgEjifBtY57mqF:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/response-handler.ts#L36)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Shouldn't all of them have the form of `(... as TheTypesTheyAre) as Response`?
</blockquote></details>

Done.
___
*[client/web/src/response-handler.ts, line 52 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3Omi65HOIl3K9tNDH:-M_4Bx5Y-pNhcD7_F7SF:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/response-handler.ts#L52)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Same here about `type`.
</blockquote></details>

Done.
___
*[client/web/src/components/panels/LayerTree.vue, line 24 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3XIneCR8hvA5iCoYa:-M_4ISEC81ZqpFBSgdSQ:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/src/components/panels/LayerTree.vue#L24)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

This seems to be resulting in the name of "UnnamedFolder" even though the shapes aren't folders (is that indicative of a bug?). Is it an easy fix to make them say "Unnamed Ellipse", "Unnamed Circle", "Unnamed Line", "Unnamed Rectangle", and "Unnamed Polygon"? If not, we can add that later.
</blockquote></details>

Done.
___
*[client/web/wasm/src/document.rs, line 128 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3UzMM9ME_yTuOfWoS:-M_4IVCb9J8QDOKjdVU8:b-iii42q) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L128)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

I'm wondering if toggle is a good idea, or if we should explicitly set the visibility to avoid some sort of state de-sync. Probably not an issue because only the change in the backend will actually cause an update to the rendering of the frontend. But maybe worth discussing more? Same also applies to the `toggle_layer_expansion` below.
</blockquote></details>

I thought about that to but came to the conclusion that if there is only one button, storing it's own state in js which might even be inconsistent with the rust state would not provide any benefit.
But as there are two buttons now, I can change that
___
*[client/web/wasm/src/document.rs, line 144 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3VRBo3ek9Z6IhOpbv:-M_4IyaRANyE-wRFoAfB:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L144)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

`new_name` would be preferable for clarity.
</blockquote></details>

Done.
___
*[client/web/wasm/src/document.rs, line 152 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3VcbsDrWXL_akgZZ-:-M_4IyuE3-RzRFAz9HB5:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L152)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Why is `name` a parameter?
</blockquote></details>

Done.
___
*[client/web/wasm/src/document.rs, line 156 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3VgqL7R3TsuvmjaX_:-M_4JDTk3L3KsOgv3-xN:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L156)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Outdated comment
</blockquote></details>

Done.

**Review by Keavon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: 1 of 13 files reviewed, 8 unresolved discussions (waiting on @Keavon and @TrueDoctor)

___
*[client/web/wasm/src/document.rs, line 128 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_3UzMM9ME_yTuOfWoS:-M_4XUZD49RkmZId5hFu:b48o5na) ([raw file](https://github.com/graphiteeditor/graphite/blob/f2ab21242e0ba0e49b9e93258198991925f273d1/client/web/wasm/src/document.rs#L128)):*
<details><summary><i>Previously, TrueDoctor wrote…</i></summary><blockquote>

I thought about that to but came to the conclusion that if there is only one button, storing it's own state in js which might even be inconsistent with the rust state would not provide any benefit.
But as there are two buttons now, I can change that
</blockquote></details>

This was a miscommunication, switching back to toggle.

**Review by Keavon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: 1 of 13 files reviewed, 9 unresolved discussions (waiting on @Keavon and @TrueDoctor)

___
*[client/web/src/components/panels/LayerTree.vue, line 17 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_4YGStEt6Meky50IHM:-M_4YGStEt6Meky50IHN:b1y56o2) ([raw file](https://github.com/graphiteeditor/graphite/blob/4fa66fb71f04ef169b2ae512479203f082ef8f10/client/web/src/components/panels/LayerTree.vue#L17)):*
> ```
> 						<IconButton @click="hideLayer(layer.path)" :size="24" title="Visible"><EyeVisible /></IconButton>
> 						<IconButton @click="showLayer(layer.path)" :size="24" title="Hidden"><EyeHidden /></IconButton>
> ```
You'll need to add back a `v-if="someVisibleCondition" to the first one and ``v-if="!someVisibleCondition" (note the `!` negation) for the second one based on the layer visibility.

**Review by Keavon — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: 1 of 13 files reviewed, 8 unresolved discussions (waiting on @Keavon and @TrueDoctor)

___
*[client/web/src/components/panels/LayerTree.vue, line 17 at r2](https://reviewable.io/reviews/graphiteeditor/graphite/107#-M_4YGStEt6Meky50IHM:-M_4Ym6RDG0jtxm2WhJL:b-vs1pr4) ([raw file](https://github.com/graphiteeditor/graphite/blob/4fa66fb71f04ef169b2ae512479203f082ef8f10/client/web/src/components/panels/LayerTree.vue#L17)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

> ```
> 						<IconButton @click="hideLayer(layer.path)" :size="24" title="Visible"><EyeVisible /></IconButton>
> 						<IconButton @click="showLayer(layer.path)" :size="24" title="Hidden"><EyeHidden /></IconButton>
> ```
You'll need to add back a `v-if="someVisibleCondition" to the first one and ``v-if="!someVisibleCondition" (note the `!` negation) for the second one based on the layer visibility.
</blockquote></details>

Looks good.

**Review by Keavon — COMMENTED** [review]
> Reviewed 9 of 12 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: all files reviewed, 7 unresolved discussions (waiting on @Keavon)

**Review by Keavon — APPROVED** [review]

**Review by Keavon — APPROVED** [review]
> Reviewed 2 of 4 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: all files reviewed, 7 unresolved discussions (waiting on @Keavon)

**Review by Keavon — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @TrueDoctor)

**Pull request merged**
