### PR TITLE
Freehand tool: Allow extension of existing paths

### PR DESCRIPTION
**Pull request by zhiyuang**
Closes https://github.com/GraphiteEditor/Graphite/issues/1549

### CODE REVIEW

**Comment by zhiyuang** [comment]
not support snapping to the anchor yet.

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
This is awesome! So much fun to play around with.

https://github.com/GraphiteEditor/Graphite/assets/4388688/fa6277b6-5fdc-4924-af97-4e9822aec16c

**Review by Keavon — APPROVED** [review]
Nice idiomatic code!

**Comment by Keavon** [comment]
@zhiyuang would you mind fixing this bug I just discovered?

https://github.com/GraphiteEditor/Graphite/assets/4388688/4257c668-68a8-4358-9545-10f718f923c4

(This also happens for rotation and scale)

**Comment by zhiyuang** [comment]
sure, I will find a time to fix this.

**Pull request merged**
