### PR TITLE
Selection history navigation with Alt+[ and Alt+] keys should filter out empty selections

### PR DESCRIPTION
**Pull request by 0SlowPoke0**

### CODE REVIEW

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
Unless I'm doing something wrong, as far as I can tell from my testing, I think this entirely breaks the whole feature? Did you test this yourself?

**Comment by 0SlowPoke0** [comment]
@Keavon  Sorry, I made a mistake in step back function, can you please check the changes I made

**Comment by Keavon** [comment]
I'll be able to check this in a week. Thanks for your patience.

**Pull request closed without merging**
