### PR TITLE
Add a selected_layers() function and refactor code to use it

### PR DESCRIPTION
**Pull request by Keavon**
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/314)

### CODE REVIEW

**Comment by Keavon** [comment]
I believe we also wanted, in this PR, to change `selected_layers_sorted` to not create a new Vec. @TrueDoctor

**Comment by TrueDoctor** [comment]
> I believe we also wanted, in this PR, to change `selected_layers_sorted` to not create a new Vec. @TrueDoctor

We actually can't because, as the name suggests, we need to sort the layers which is not possible without collecting them first

**Comment by AyeTbk** [comment]
Should these methods (`selected_layers_sorted` and `selected_layers`) be in document_file.rs, on the `Document` type, instead of in document_message_handler.rs? To render the selection's bounding box in #282, the selected layers are needed (I currently compute them on my own, but I would like to reuse a prexisting method, if there is one). It also makes more sense to me for the `Document` to tell us what its selected layers are, instead of having code externalto it having to toy with its innards to determine them...

**Comment by TrueDoctor** [comment]
That sounds like a good idea

**Comment by Keavon** [comment]
> That sounds like a good idea

@TrueDoctor Is that a change you could make then merge this? I only just realized we hadn't merged this yet. I am not sure I understand exactly what change to make per AyeTbk's suggestions.

**Comment by TrueDoctor** [comment]
> > That sounds like a good idea
> 
> @TrueDoctor Is that a change you could make then merge this? I only just realized we hadn't merged this yet. I am not sure I understand exactly what change to make per AyeTbk's suggestions.

Oh lol, I tought rhis code had already been merged xD

**Comment by TrueDoctor** [comment]
I dont think this pr is conceptually the right place to make that change.
The pr does what it says on the label and that is a good thing

**Comment by TrueDoctor** [comment]
> Should this method (`selected_layers`) be in document_file.rs, on the `Document` type, instead of in document_message_handler.rs? To render the selection's bounding box in #282, the selected layers are needed (I currently compute them on my own, but I would like to reuse a prexisting method, if there is one). It also makes more sense to me for the `Document` to tell us what its selected layers are, instead of having code external to it having to toy with its innards to determine them...
> (this goes for a lot of the methods in document_message_handler, I guess)

I think we should do a seperate pr in which we move lines 131-202 into the document_file but it makes sense to move them as a bunch

**Comment by TrueDoctor** [comment]
I will address the movement to the document file + further refactoring in the upcoming transforms api

**Pull request merged**
