### PR TITLE
New nodes: Resample Points, Spline from Points

### PR DESCRIPTION
**Pull request by Chase-Percy**
Part of #912

### CODE REVIEW

**Comment by Keavon** [comment]
Hi, can you please remind (or update) me of the status of this issue? Thanks!

**Comment by Chase-Percy** [comment]
> Hi, can you please remind (or update) me of the status of this PR? Thanks!

Hey sorry just saw this. The last update I had is in the discord task help section. It's mostly done except for an edge case I posted about.

**Comment by Keavon** [comment]
"Density" should probably be renamed "Spacing" since it's the inverse of density.

**Comment by Keavon** [comment]
The fact that this works on text now makes this my favorite node!

image

But unfortunately it seems to be broken for shapes created with these tools:

- Line
- Rectangle
- Ellipse
- Polygon

The others work, even with closed shapes. @0HyperCube do you have any ideas why that might be?

**Comment by 0HyperCube** [comment]
@Keavon Works fine. Note that the spacing is specified in vector data space so the rectangle / line / ellipse / polygon which are unit size require a spacing of <1.

**Comment by Keavon** [comment]
@0HyperCube Oh, I see. Would that be difficult to solve by making it use the current transform?

**Review by Keavon — APPROVED** [review]

**Pull request merged**
