### PR TITLE
Bundle graphite using Tauri

### LINKED ISSUE #636: Set up downloadable builds through Tauri
[Tauri](https://tauri.studio/) is an Electron alternative that uses the local OS's webview to provide a low-overhead web wrapper as a desktop app. It's part of the Rust ecosystem.
This is actually something we can tackle sooner than I was previously expecting.

- [ ] We should probably wait to switch to Svelte (#635), but this isn't a strict blocker
- [x] We should probably wait for Tauri's official 1.0 release ~~(as of writing, it's at the release candidate stage)~~ ([Released](https://tauri.app/blog/2022/06/19/tauri-1-0))
- [ ] We will want to configure our build infrastructure to provide [binaries](https://tauri.studio/guides/distribution/publishing) and [automatic updates](https://tauri.studio/guides/distribution/updater) as part of the deployment process
- [ ] And we'll want to add some in-app functionality to nicely prompt to install updates

Longer-term:
- We'll want to run the Rust code natively instead of inside the webview's WASM runtime, especially once we're doing our own rendering rather than using the browser's SVG engine (since the perf bottleneck is currently on that render engine, not ours)
- Tauri will be useful for hosting the [Monaco code editor](https://microsoft.github.io/monaco-editor/) for node source code editing

### PR DESCRIPTION
**Pull request by TrueDoctor**
Closes #636

### CODE REVIEW

**Comment by felipetesc** [comment]
https://github.com/felipetesc/graphite-desktop
print

**Comment by TrueDoctor** [comment]
> https://github.com/felipetesc/graphite-desktop print

Well lol, didn't know that existed xD

**Comment by TrueDoctor** [comment]
@felipetesc Did you have similar issues with `instantiateStreaming` receiving the wrong mime type in `cargo tauri build`?
The aim of this pr is a bit different because we acutally aim to execute the logic locally in order not to be limited by wasm constraints. Would you mind taking a look at this pr and potentially help with some of the issues?
I'm a total newbie to tauri hence any feedback would be much appreciated.

**Comment by felipetesc** [comment]
> @felipetesc Did you have similar issues with `instantiateStreaming` receiving the wrong mime type in `cargo tauri build`? The aim of this pr is a bit different because we acutally aim to execute the logic locally in order not to be limited by wasm constraints. Would you mind taking a look at this pr and potentially help with some of the issues? I'm a total newbie to tauri hence any feedback would be much appreciated.

Sorry, I misplaced where this message should be added
I will answer at :  
[Set up downloadable builds through Tauri](https://github.com/GraphiteEditor/Graphite/issues/636https://github.com/GraphiteEditor/Graphite/issues/636)

**Comment by TrueDoctor** [comment]
All seems to work fine from my testing, merging this now to allow others to work based on this pr. Post merge reviews welcome

**Pull request merged**
