### PR TITLE
Make copying/duplicating nodes not preserve the incoming connection

### PR DESCRIPTION
**Pull request by 0HyperCube**
Remove wires to nodes outside of copy, as mentioned in the discord todo list.

### CODE REVIEW

**Comment by Keavon** [comment]
<kbd>Ctrl</kbd><kbd>D</kbd> doesn't seem to be working anymore as far as I can tell.

**Comment by 0HyperCube** [comment]
Looks like I cleared the selected nodes list before duplicating the nodes 🙃.

**Comment by Keavon** [comment]
Would it be possible (read: easy) to, when pasting a node, check if that space is occupied and shift it down similar to Ctrl+D in that circumstance? Or maybe the easier route of just applying the offset to all pastes would be a reasonable stopgap. I realize the contracts my original spec that Ctrl+D offsets while Ctrl+V doesn't, but now that I've tried it out, I am concerned about overlapping nodes causing confusion.

**Comment by Keavon** [comment]
Works perfect! 😄

**Review by Keavon — APPROVED** [review]

**Pull request merged**
