### PR TITLE
Change the select tool to immediately start dragging when clicking a shape

### LINKED ISSUE #426: Support clicking and dragging on a non-selected shape to select it
Currently a non-selected shape must be clicked on, then dragged. It should be possible to click and drag in one interaction.

### PR DESCRIPTION
**Pull request by TrueDoctor**
Closes #426

### CODE REVIEW

**Comment by Keavon** [comment]
It's not possible to click to select a shape. Try clicking on a shape without dragging your mouse at all.

**Comment by otdavies** [comment]
I tested this and it appears to work in all my testing scenarios. Feels good and works well. Didn't observe any issues. Changes to select.rs seem sane.

**Comment by TrueDoctor** [comment]
Got the operation order mixed up during the pre commit cleanup, changed it back and should work as expected now

**Comment by Keavon** [comment]
Much better! Last problem I notice: <kbd>Shift</kbd>-clicking layers in the viewport no longer adds to the selection, it instead replaces the selection.

**Review by Keavon — APPROVED** [review]

**Pull request merged**
