### PR TITLE
Fix point nudging to work in document space

### LINKED ISSUE #2083: Path tool point nudging should be in document coordinates, not viewport coordinates
If you select a point using the Path tool and nudge it to the right by 10 units with <kbd>Shift</kbd><kbd>Right Arrow</kbd>, starting at 100% viewport zoom but then zooming to 200%, you'll notice it takes two presses of <kbd>Shift</kbd><kbd>Left Arrow</kbd> to return back to its starting place. That's because it currently is moving relative to the viewport coordinates, but it should always work relative to the document coordinates so 10 units to the right means the same thing regardless of the current level of zoom. It also shouldn't be in the layer's local coordinate space, where a shape that has a 0.1 scale factor would take 10 times as many presses to travel the intended distance. The Select tool's nudging can be referenced for this, because it works correctly in document space (not layer-local or viewport space).

### PR DESCRIPTION
**Pull request by November-6**
Closes #2083

### CODE REVIEW

**Comment by Keavon** [comment]
!build

**Review by Keavon — APPROVED** [review]
Thank you!

**Comment by November-6** [comment]
Thanks for the notes! 
I'll get working on it as soon as i get back from college today. In the mean time, can you suggest me some place where i can learn more about the specific maths used in this project?

Regards :)

**Comment by Keavon** [comment]
Are you referring to the TODO comment I left in my latest commit? That's not something you need to take action on. This PR is ready to merge.

**Pull request merged**
