### PR TITLE
Curves image adjustment node

### PR DESCRIPTION
**Pull request by nat-rix**

### CODE REVIEW

**Comment by Keavon** [comment]
Looks like this is taking shape and starting to work now! I'm noticing that it breaks (and throws a console error) after a little while of dragging the points around, at which point the laggy UI stops being laggy (since it's not doing anything anymore from then on).

**Comment by nat-rix** [comment]
> I'm noticing that it breaks (and throws a console error) after a little while of dragging the points around

Could you please provide an error log? I can't reproduce that.

**Comment by Keavon** [comment]
> Could you please provide an error log? I can't reproduce that.

It should definitely just happen by using it for a bit, maybe try and be aggressive and drag it around a lot every frame. I'm using Chrome in case that makes any difference. I'm adding this downstream of the Downscale node for a 4000x3000 image. The only error it prints is this:

image

Note, that is not referring to hitting a Rust `unreachable!();` macro, but rather [this wasm instruction](https://developer.mozilla.org/en-US/docs/WebAssembly/Reference/Control_flow/unreachable).

**Comment by nat-rix** [comment]
Huh, interesting. This looks like an out of memory error. My first intuition is that this happens, because too many non-completed events stack up in the event queue. But I'll have
a look into this a bit later

**Comment by nat-rix** [comment]
The bug is also happening on master when using e.g. the blend node. I think this is probably "normal", when storing such a huge image uncompressed and then making clones of it. But to be sure, I'll investigate further, which kind of `TaggedValue` is cloned there for which reason to produce an oom.

**Comment by Keavon** [comment]
Okay, good to know it's not an issue with the curves node, just a symptom of making frequent adjustments. Weird that the Downscale node isn't mitigating. I'll use smaller images to test from now on. Thanks for creating an issue for that.

**Comment by TrueDoctor** [comment]
I've updated the branch to use the new master, I think it makes sense to merge this pretty soon (even if it is not completely done) to prevent further code rot

**Comment by TrueDoctor** [comment]
This does acutally work surprisingly well, I can fix the tests and I think we might be good to merge then

**Comment by Keavon** [comment]
I built this branch and don't see the Curves node in the layer add menu, do you know what's up with that?

**Comment by TrueDoctor** [comment]
@nat-rix do you know what would most likely be the culprit for the failing tests?

**Comment by TrueDoctor** [comment]
> I built this branch and don't see the Curves node in the layer add menu, do you know what's up with that?

The build link works, can you retry that?

**Comment by TrueDoctor** [comment]
@Keavon It is unfortunate you had to revert the brightness contrast changes. It would be very good if we could reuse that code instead of duplicating the entire file + we lose the improvements to the code structure

**Comment by Keavon** [comment]
Yes, but that'll have to be a future contributor's task since the more important priority right now is just getting this merged in its current (plus slightly fixed up) state. You reminded me that I forgot to commit the TODO comment about replacing that someday.

**Review by Keavon — APPROVED** [review]

**Comment by Keavon** [comment]
Hi @nat-rix, thanks again for this code contribution to the project! We're still hoping you will respond to the request to relicense this code. Please see #4208 ASAP, thank you!

**Comment by Keavon** [comment]
Hi @nat-rix, we're grateful of your past code contribution to Graphite, but unless we hear from you by the **end of this weekend** with agreement about relicensing your code to include the MIT license, we will begin steps to remove your code contributions **so that you will no longer be a Graphite code contributor**. We'd much rather avoid this outcome, so please respond now.

To agree, simply log into your GitHub account, visit https://github.com/GraphiteEditor/Graphite/pull/4208, and copy-paste this into a comment:

"I license my past and future contributions to Graphite under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option."

If you're hesitant because you disagree or have questions, feel free to respond with another message; we'll do our best to answer your questions or concerns. More explanation is at the top of the linked thread if you're confused. **So far, 164 contributors have agreed and you are among the 11% remaining** whom we are still hoping to hear from before we begin removing your code from the project starting this Monday. (If you only see this later than Monday, your future belated response will still be appreciated.)

Thank you for your cooperation and support of open source, and we hope you'll help us keep your valued contributions in-tact.

**Pull request merged**
