### PR TITLE
Fix new document position

### PR DESCRIPTION
**Pull request by 0HyperCube**
A new document had its (0,0) in the top left of the screen instead of in the centre until the document was moved. This fixes that.

### CODE REVIEW

**Comment by Keavon** [comment]
Thanks for the quick PR!

After glancing at the code real quick, I'm wondering why the original default document correctly is centered but other new documents require a special new function specifically for a centered transform? Shouldn't the initial document and later new documents be the same, and this problem thus fixed the same way the initial document is centered?

**Comment by 0HyperCube** [comment]
@Keavon The js is sending a resize event (`bounds_of_viewports`) which adjusts the position to be in the centre.

**Comment by Keavon** [comment]
Ah, I see. Could you please explain the reasoning for adding a new constructor function, versus just fixing the behavior in `with_name()` and `with_name_and_content()`? I can't imagine we'd ever want to call either of those constructor functions with the incorrect centering behavior.

Please also move those constructor functions to the top of the `impl` block, I notice right now they are weirdly hidden in the middle of the other functions.

**Comment by 0HyperCube** [comment]
@Keavon My reasoning was that decoding the string didn't need the document to be centred (as its position would be overridden anyway) but it doesn't really matter either way.

**Review by Keavon — APPROVED** [review]

**Pull request merged**
