### PR TITLE
Refactor document node type lookup function to fix performance degradation over time

### LINKED ISSUE #1913: Performance leak when many layers are in a scene
It initially accounts for half the frame time, and gets worse and worse over time until you reload the editor.

### PR DESCRIPTION
**Pull request by TrueDoctor**
Closes #1913

### CODE REVIEW

**Comment by TrueDoctor** [comment]
This is now only bound on mem copys for sending the data from the node runtime to the frontend. This indicates that we might need a diff based api to fully solve this issue

**Comment by TrueDoctor** [comment]
The document type lookup which took previously about 50% of the frame time on the Sakura artwork has now basically disappeard from the flamegraph:
image

**Comment by TrueDoctor** [comment]
Noticed a bug where when opening the same document twice and then closing one of them, types disappear

**Comment by TrueDoctor** [comment]
Fixed

**Review by Keavon — APPROVED** [review]
Incredible improvement! And nice attention to detail on the doc comments, too.

**Pull request merged**
