### PR TITLE
Implement popover component and beginnings of color picker

### PR DESCRIPTION
**Pull request by Keavon**
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/128)

### CODE REVIEW

**Comment by TrueDoctor** [comment]
Is it possible to make the color picker go away when you click somewhere else on the screen?

**Comment by Keavon** [comment]
Yes, but that's an extra layer of complexity I will be adding to the popover system later.

**Review by TrueDoctor — APPROVED** [review]
Looks fine as far as I can tell

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/128#-:-M_vhmmrDNWqNICWfyVf:bs95qw4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Keavon)

**Pull request merged**
