### PR TITLE
⬠ Add polygon drawing tool

### PR DESCRIPTION
**Pull request by 0HyperCube**
⬠ Add the polygon drawing tool. I had to implement `kurbo::shape` as there was not a shape for polygons. The number of sides is currently hardcoded in at the bottom of `shape.rs` but it should be moved into the context menu at the top.

---
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)

### CODE REVIEW

**Review by Keavon — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: all files reviewed, 7 unresolved discussions (waiting on @0HyperCube)

___
*[core/document/src/lib.rs, line 31 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQQBoi1Mhk8FkCt5gN:-MYQQBoi1Mhk8FkCt5gO:b-2h938b) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/lib.rs#L31)):*
> ```XML
> 			Self::Shape(s) => {
> 				format!(r#"<polygon points="{}" style="fill: #fff; stroke: white;" />"#, s)
> 			}
> ```

Let's skip the stroke color for consistency with the other shapes. But of course that will be replaced by the actual color system soon enough.
___
*[core/document/src/shape_points.rs, line 38 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQT3o62hewvkiQgHVx:-MYQT3o62hewvkiQgHVy:b-v7n84y) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L38)):*
> ```XML
> 	// Gets the length of one side
> 	#[inline]
> 	pub fn side(&self) -> f64 {
> ```

Maybe it's better to call this `side_length`?
___
*[core/document/src/shape_points.rs, line 46 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQTRALAEp39hu2siTF:-MYQTRALAEp39hu2siTG:b-heca2h) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L46)):*
> ```XML
> 	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
> 		fn rotate(v: &Vec2, theta: f64) -> Vec2 {
> 			let cs = theta.cos();
> ```

Nit: In the effort of nonabbreviated variable names, how about using `sine` and `cosine` as the variable names?
___
*[core/document/src/shape_points.rs, line 73 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQVbTO5vgbzP-cV7v4:-MYQVbTV60nMFvIwoOcJ:b-hebyk9) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L73)):*
> ```XML
> 	fn next(&mut self) -> Option<PathEl> {
> 		fn rotate(v: &Vec2, theta: f64) -> Vec2 {
> 			let cs = theta.cos();
> ```

Here too, thanks 😊
___
*[core/document/src/shape_points.rs, line 94 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQW28K4TioKz8JEUTa:-MYQW28K4TioKz8JEUTb:ba8xgq4) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L94)):*
> ```XML
> 
> 	#[inline]
> 	fn add(self, v: Vec2) -> ShapePoints {
> ```

What does the parameter `v` stand for?
___
*[core/document/src/shape_points.rs, line 126 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQWHK6CNA6s1gjK6rE:-MYQWHK6CNA6s1gjK6rF:b487q5e) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L126)):*
> ```XML
> 		todo!()
> 	}
> }
> ```

Awesome job on this file!!
___
*[core/editor/src/dispatcher/events.rs, line 118 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQW_MMA1ueh1L0giWy:-MYQW_MN254M5dDpUmXe:b-muy7v6) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/editor/src/dispatcher/events.rs#L118)):*
> ```XML
> 	KeyX,
> 	KeyZ,
> 	KeyS,
> ```

Let's use "N" as the shortcut (for "ngon").

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: all files reviewed, 7 unresolved discussions (waiting on @0HyperCube and @Keavon)

___
*[core/document/src/shape_points.rs, line 94 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQW28K4TioKz8JEUTa:-MYU3SMJ49oE_vZOpbug:b-hfuib) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L94)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

What does the parameter `v` stand for?
</blockquote></details>

@keavon  It stands for vec, it is the same in the kurbo source for circles and rectangles.

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: all files reviewed, 7 unresolved discussions (waiting on @0HyperCube and @Keavon)

___
*[core/document/src/shape_points.rs, line 126 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQWHK6CNA6s1gjK6rE:-MYU49q7-8rZxqi5gcXl:b-zcjvte) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L126)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Awesome job on this file!!
</blockquote></details>

Thanks

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: all files reviewed, 7 unresolved discussions (waiting on @0HyperCube and @Keavon)

___
*[core/document/src/shape_points.rs, line 46 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQTRALAEp39hu2siTF:-MYU4FBH56MIR8gWp6bO:b-11hobv) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L46)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Nit: In the effort of nonabbreviated variable names, how about using `sine` and `cosine` as the variable names?
</blockquote></details>

Alright!

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: all files reviewed, 7 unresolved discussions (waiting on @0HyperCube and @Keavon)

___
*[core/document/src/shape_points.rs, line 38 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQT3o62hewvkiQgHVx:-MYU4Nuv0tghpiMJGKRJ:b2aag2o) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L38)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Maybe it's better to call this `side_length`?
</blockquote></details>

Probably, I'll fix that now.

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: all files reviewed, 7 unresolved discussions (waiting on @0HyperCube and @Keavon)

___
*[core/document/src/lib.rs, line 31 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQQBoi1Mhk8FkCt5gN:-MYU6vRy8D4x364IvrRh:b-hfh92n) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/lib.rs#L31)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Let's skip the stroke color for consistency with the other shapes. But of course that will be replaced by the actual color system soon enough.
</blockquote></details>

Sounds fine
___
*[core/document/src/shape_points.rs, line 94 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQW28K4TioKz8JEUTa:-MYU55GD9rwujpIuIto3:bjvvylf) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L94)):*
> side_length

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: all files reviewed, 7 unresolved discussions (waiting on @0HyperCube and @Keavon)

___
*[core/document/src/shape_points.rs, line 94 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQW28K4TioKz8JEUTa:-MYUALmYCNqL16InZgLi:b-ve10ih) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L94)):*
<details><summary><i>Previously, 0HyperCube wrote…</i></summary><blockquote>

> side_length
</blockquote></details>

I changed it to movement.

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: 3 of 9 files reviewed, 7 unresolved discussions (waiting on @Keavon)

___
*[core/document/src/shape_points.rs, line 73 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQVbTO5vgbzP-cV7v4:-MYUAQv24E6OgrivfpIP:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L73)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Here too, thanks 😊
</blockquote></details>

Done.
___
*[core/editor/src/dispatcher/events.rs, line 118 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQW_MMA1ueh1L0giWy:-MYUPCGu7S_pBR0u5mYv:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/editor/src/dispatcher/events.rs#L118)):*
<details><summary><i>Previously, Keavon (Keavon Chambers) wrote…</i></summary><blockquote>

Let's use "N" as the shortcut (for "ngon").
</blockquote></details>

Done.

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: 3 of 9 files reviewed, 7 unresolved discussions (waiting on @Keavon)

___
*[core/document/src/lib.rs, line 31 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQQBoi1Mhk8FkCt5gN:-MYVklIW2toyh2g-7ym7:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/lib.rs#L31)):*
<details><summary><i>Previously, 0HyperCube wrote…</i></summary><blockquote>

Sounds fine
</blockquote></details>

Done.

**Review by 0HyperCube — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/75)* status: 3 of 9 files reviewed, 7 unresolved discussions (waiting on @Keavon)

___
*[core/document/src/shape_points.rs, line 38 at r1](https://reviewable.io/reviews/graphiteeditor/graphite/75#-MYQT3o62hewvkiQgHVx:-MYVksgW-K58AMlsxzEZ:b-896fix) ([raw file](https://github.com/graphiteeditor/graphite/blob/34d014762f30cba9b4bad60102f74c8421aa4c02/core/document/src/shape_points.rs#L38)):*
<details><summary><i>Previously, 0HyperCube wrote…</i></summary><blockquote>

Probably, I'll fix that now.
</blockquote></details>

Done.

**Review by Keavon — APPROVED** [review]

**Review by Keavon — APPROVED** [review]

**Pull request merged**
